#!/usr/bin/env node
var Promise = require("bluebird");
var lib = require("..");
lib.handlers.enable = true;

var chalk = require('chalk')

console.log("transaction resolver")

var argv = require('minimist')(process.argv.slice(2), 
  { default: 
    { size: 100
    , nconc: 2
    , toEnabled: 0 
    , gapMS: 3000
    , txOffset: 0
    , strato: "http://localhost/strato-api"
    }
  }
);

var size = argv.size;
var gapMS = argv.gapMS;
var nconc = argv.nconc;
var toEnabled = argv.toEnabled;
var txOffset = argv.txOffset;

lib.setProfile("ethereum-frontier", argv.strato);

var privkey = lib.ethbase.Crypto.PrivateKey.random();
var address = privkey.toAddress();
var account = lib.ethbase.Account(privkey.toAddress());

console.log("Address is: " + address);


var faucet = lib.routes.faucet(address)
  .then(a => {
    console.log("Faucet called for " + a.address); return a.address})
  .then(a =>{
     account.balance.then(b => {
       console.log("balance is: " + b.toString());
     }).then(aa => {

       account.nonce.then(n => {
         console.log("current nonce: " + n);

         var toSend = [];
         for(var i = 0; i < nconc; i++){a
           toSend.push(sendBatch(n, i))
         }
    
         return Promise.all(toSend);
       })
       .then(console.log("Done!"))
     })
  });


// // If I remove this, I fet handler issues
// var compileContract = lib.Solidity(`
// contract C{}
// `).call("construct");
// 
// var createContract = faucet.
//   thenReturn(compileContract).
//   call("callFrom", privkey).
//   get("contract");

var currentNonce = 0;
var startTime;
var batchesDispatched = 0;

var sendBatch = function(nonce, concNum){

  var c = (concNum == 0) ? chalk.green : (a=>chalk.blue('\t\t\t\t\t\t\t'+a));

  process.stdout.write(c("# Sending " + size + " transactions\n"));

  var txList = [];
  for (i = 0; i < size; ++i) {
    var tx = lib.ethbase.Transaction({nonce: nonce + i + txOffset});
    tx.value = "0";
    //tx.from = address;
    if(toEnabled==1)
      tx.to   = "e1fd0d4a52b75a694de8b55528ad48e2e2cf7859";
    if(toEnabled==2)
      tx.to   = address;
    tx.sign(privkey);
    txList.push(tx);
    //tx.send(privkey, tx.to).then(r => {
    //  console.log("Result: " + JSON.stringify(r))
    //})
    process.stdout.write(c("tx: " + JSON.stringify(tx) + "\n\n"));
  }

  //return lib.ethbase.Transaction.sendList(txList, privkey)
  return lib.routes.submitTransactionList(txList);
}

